name: DeployToGitHubPages
env:
  PUBLISH_DIR: bin/Release/net5.0.0/publish/wwwroot
  NAME: blzor8

# Controls when the action will run
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Test .Net
      run: dotnet test

    - name: Publish app
      run: dotnet publish ${{ env.NAME }}.csproj -c Release
      
    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /${{ env.NAME }}.csproj/
      
    - name: GitHub Pages action
      if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.PUBLISH_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ${{ env.PUBLISH_DIR }}
        allow_empty_commit: false
        keep_files: false
        force_orphan: true
        # TODO uncomment the following line if you have a custom domain name
        # cname: demo.meziantou.net
